name: Android APK Builder

on:
  push:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-22.04
    timeout-minutes: 90

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install system dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y \
            git zip unzip python3-pip python3-venv \
            openjdk-17-jdk autoconf libtool pkg-config \
            zlib1g-dev libncurses5-dev cython3

      - name: Install Buildozer
        run: |
          pip install --upgrade pip wheel
          pip install buildozer cython==0.29.33

      - name: Install Android SDK components
        run: |
          mkdir -p ~/.android
          touch ~/.android/repositories.cfg

          mkdir -p ~/android-sdk
          cd ~/android-sdk
          wget https://dl.google.com/android/repository/commandlinetools-linux-9477386_latest.zip
          unzip commandlinetools-linux-*.zip
          rm commandlinetools-linux-*.zip
          mv cmdline-tools latest
          mkdir -p cmdline-tools
          mv latest cmdline-tools/

          yes | ~/android-sdk/cmdline-tools/latest/bin/sdkmanager --licenses || true
          yes | ~/android-sdk/cmdline-tools/latest/bin/sdkmanager --update
          yes | ~/android-sdk/cmdline-tools/latest/bin/sdkmanager "platform-tools" "build-tools;30.0.3" "platforms;android-30"

          chmod +x ~/android-sdk/build-tools/30.0.3/aidl
          ~/android-sdk/build-tools/30.0.3/aidl --version || true

      - name: Configure environment
        run: |
          echo "ANDROID_SDK_ROOT=$HOME/android-sdk" >> $GITHUB_ENV
          echo "PATH=$HOME/android-sdk/platform-tools:$HOME/android-sdk/build-tools/30.0.3:$HOME/android-sdk/cmdline-tools/latest/bin:$PATH" >> $GITHUB_ENV

      - name: Export Android SDK Paths
        run: |
          echo "$HOME/android-sdk/platform-tools" >> $GITHUB_PATH
          echo "$HOME/android-sdk/build-tools/30.0.3" >> $GITHUB_PATH
          echo "$HOME/android-sdk/cmdline-tools/latest/bin" >> $GITHUB_PATH

      - name: Symlink SDK to expected location
        run: |
          mkdir -p .buildozer/android/platform/
          ln -s $HOME/android-sdk .buildozer/android/platform/android-sdk

      - name: Create buildozer.spec
        run: |
          cat > buildozer.spec << EOL
          [app]
          title = MyApp
          package.name = myapp
          package.domain = org.test
          source.dir = .
          source.include_exts = py,png,jpg,kv,atlas
          version = 0.1
          requirements = python3,kivy
          orientation = portrait

          [buildozer]
          log_level = 2
          warn_on_root = 1
          android.sdk_path = /home/runner/android-sdk
          android.ndk_path = /home/runner/.buildozer/android/platform/android-ndk
          android.accept_sdk_license = True
          android.arch = armeabi-v7a
          android.build_tools_version = 30.0.3
          android.api = 30
          EOL

      - name: Build APK
        run: |
          rm -rf .buildozer bin
          buildozer -v android debug || (find .buildozer/android/platform -name build.output -exec cat {} \; && exit 1)
          if [ ! -f bin/*.apk ]; then
            echo "APK not found!"
            exit 1
          fi

      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: android-app
          path: bin/*.apk
