name: Android APK Builder

on:
  push:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-22.04
    timeout-minutes: 90

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install system dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y \
            git zip unzip python3-pip python3-venv \
            openjdk-17-jdk autoconf libtool pkg-config \
            zlib1g-dev libncurses5-dev cython3

      - name: Install Buildozer
        run: |
          pip install --upgrade pip wheel
          pip install buildozer cython==0.29.33

      - name: Setup Android SDK and NDK
        run: |
          # Create directories
          mkdir -p ~/android-sdk
          mkdir -p ~/.buildozer/android/platform
          
          # Install Command Line Tools
          cd ~/android-sdk
          wget https://dl.google.com/android/repository/commandlinetools-linux-9477386_latest.zip
          unzip commandlinetools-linux-*.zip
          rm commandlinetools-linux-*.zip
          mv cmdline-tools latest
          mkdir -p cmdline-tools
          mv latest cmdline-tools/
          
          # Create complete SDK directory structure that Buildozer expects
          mkdir -p ~/.buildozer/android/platform/android-sdk
          ln -s ~/android-sdk/cmdline-tools ~/.buildozer/android/platform/android-sdk/cmdline-tools
          ln -s ~/android-sdk/platform-tools ~/.buildozer/android/platform/android-sdk/platform-tools
          ln -s ~/android-sdk/build-tools ~/.buildozer/android/platform/android-sdk/build-tools
          ln -s ~/android-sdk/platforms ~/.buildozer/android/platform/android-sdk/platforms
          
          # Accept licenses
          yes | ~/android-sdk/cmdline-tools/latest/bin/sdkmanager --licenses
          
          # Install specific versions
          ~/android-sdk/cmdline-tools/latest/bin/sdkmanager "platform-tools" "build-tools;34.0.0" "platforms;android-34"
          
          # Install NDK
          ~/android-sdk/cmdline-tools/latest/bin/sdkmanager "ndk;25.1.8937393"
          ln -s ~/android-sdk/ndk/25.1.8937393 ~/.buildozer/android/platform/android-ndk-r25b

      - name: Configure environment
        run: |
          echo "ANDROID_SDK_ROOT=$HOME/android-sdk" >> $GITHUB_ENV
          echo "ANDROID_HOME=$HOME/android-sdk" >> $GITHUB_ENV
          echo "ANDROID_NDK_HOME=$HOME/android-sdk/ndk/25.1.8937393" >> $GITHUB_ENV
          echo "PATH=$PATH:$HOME/android-sdk/platform-tools:$HOME/android-sdk/build-tools/34.0.0:$HOME/android-sdk/cmdline-tools/latest/bin:$HOME/android-sdk/ndk/25.1.8937393" >> $GITHUB_ENV

      - name: Create buildozer.spec
        run: |
          cat > buildozer.spec << EOL
          [app]
          title = MyApp
          package.name = myapp
          package.domain = org.test
          source.dir = .
          source.include_exts = py,png,jpg,kv,atlas
          version = 0.1
          requirements = python3,kivy
          orientation = portrait
          
          [buildozer]
          log_level = 2
          warn_on_root = 1
          android.sdk_path = $HOME/android-sdk
          android.ndk_path = $HOME/android-sdk/ndk/25.1.8937393
          android.accept_sdk_license = True
          android.arch = arm64-v8a
          android.build_tools_version = 34.0.0
          android.api = 34
          android.minapi = 21
          EOL

      - name: Build APK
        run: |
          # Clean previous builds
          rm -rf .buildozer bin
          mkdir -p bin
          
          # Run buildozer with full logging
          buildozer -v android debug > build.log 2>&1 || (cat build.log && exit 1)
          
          # Verify APK exists
          if [ ! -f bin/*.apk ]; then
            echo "APK not found!"
            cat build.log
            exit 1
          fi

      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: android-app
          path: bin/*.apk
